language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run build_lib
  #- npm run test-headless
  - ng build ng-paginaion --prod --base-href https://rulorules99.github.io/ng-rga-paginaion/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: a0e1627c162f9ea07c0e11fca7e1e6ab231c82e3
  local_dir: dist/ng-paginaion
  on:
    branch: master
#ad946ef9b395ddf50cbf61ca1675078de007f76b
#2c209a3c00f11d388a66c6d2b94a3e8acfa8df81
#a0e1627c162f9ea07c0e11fca7e1e6ab231c82e3
#$GITHUB_TOKEN