version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test